### ISSUE TITLE
[FEATURE] Bot Hosting so it always stays online

### ISSUE THREAD

**Issue by Yeffian** [anf/BotANF#37]
**Is your feature request related to a problem? Please describe.**
If the bot were always online, we could always test and report bugs with it, instead of having to wait for the bot to come online.

**Describe the solution you'd like**
Using a service like Heroku to keep the bt online 24/7. Since the bot is written in Typescript, Heroku should support it. Of course, if any of you think of an alternative solution, by all means, do it.

**Comment by anf** [comment]
This version is a development version and long discussions (most with myself, some with the team) have been going. The code itself isn't even capable of displaying a proper help command. This is not planned currently due to this reason which means we cannot host it on Heroku yet.
