### ISSUE TITLE
[FEATURE] Use Microsoft C#'s naming conventions

### ISSUE THREAD

**Issue by anf** [anf/BotANF#8]
**Is your feature request related to a problem? Please describe.**
Microsoft's naming conventions are not followed.

**Describe the solution you'd like**
It's important to follow naming conventions, following those will improve the code structure and readability. So I'd like this to be enforced.
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/general-structure-of-a-csharp-program

**Additional context**
Add this naming convention to the Code of Conduct and also notify it in the contributing file. *And* change the current structure if and wherever the usage has not been previously followed.

**Comment by tomlin7** [comment]
I upvote this. Add this to contributing

**Comment by anf** [comment]
Implemented with [master/c7c8e3c](https://github.com/ANF-Studios/BotANF/commit/c7c8e3c82f163597e7cc6af65848174c6887a6ab)
